HIVIEWRENDERER_SITE = https://gitlab.fmsoft.cn/hybridos/hiviewrenderer
HIVIEWRENDERER_VERSION = 91fee146cc1412d5e59ca94ff934935875a6e457
HIVIEWRENDERER_SITE_METHOD = git
HIVIEWRENDERER_INSTALL_STAGING = YES
HIVIEWRENDERER_DEPENDENCIES = hiwebkit

$(eval $(cmake-package))
