HIACEJS_SITE = https://gitlab.fmsoft.cn/hybridos/hiACEJS
HIACEJS_VERSION = b83d7b13f994627da4579b646b19974d69b5060f
HIACEJS_SITE_METHOD = git
HIACEJS_INSTALL_STAGING = YES

HIACEJS_DEPENDENCIES = jpeg libpng freetype jerryscript bounds_checking_function mbedtls minigui

HIACEJS_CONF_OPTS = \
	-DCMAKE_BUILD_TYPE=MinSizeRel \
	-DEXTERNAL_COMPILE_FLAGS=-Wno-unused-function \
	-DBUILD_SHARED_LIBS=ON \
	-DJERRY_CMDLINE_SNAPSHOT=ON \
	-DJERRY_ERROR_MESSAGES=ON \
	-DJERRY_LOGGING=ON \
	-DJERRY_GLOBAL_HEAP_SIZE=20480 \
	-DJERRY_MEM_STATS=ON \
	-DJERRY_PROFILE=es5.1 \
	-DJERRY_SNAPSHOT_EXEC=ON \
	-DJERRY_SNAPSHOT_SAVE=ON \
	-DEXTERNAL_COMPILE_FLAGS="-Wno-unused-function"

$(eval $(cmake-package))
