HYBRIDOS_LITE_DEMO_SITE = https://gitlab.fmsoft.cn/hybridos/hybridos-lite
HYBRIDOS_LITE_DEMO_VERSION = 8bf92fc04d2c39e13c3ffb5009167d104ec3653a
HYBRIDOS_LITE_DEMO_SITE_METHOD = git
HYBRIDOS_LITE_DEMO_INSTALL_STAGING = YES
HYBRIDOS_LITE_DEMO_DEPENDENCIES = libglib2 minigui mgeff hicairo hicairo hisvg

define HYBRIDOS_LITE_DEMO_INSTALL_CONFIG
    $(INSTALL) -c -m 644 $(HYBRIDOS_LITE_DEMO_PKGDIR)/MiniGUI.cfg $(TARGET_DIR)/usr/libexec
endef
HYBRIDOS_LITE_DEMO_POST_INSTALL_TARGET_HOOKS += HYBRIDOS_LITE_DEMO_INSTALL_CONFIG

$(eval $(cmake-package))
